//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 2005-2014 Simon Howard
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// DESCRIPTION: Event handling.
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//

#include <stdlib.h>
#include "d_event.h"

#define MAXEVENTS 64

static event_t events[MAXEVENTS];
static int eventhead;
static int eventtail;

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
    eventhead = (eventhead + 1) % MAXEVENTS;
}

// Read an event from the queue.

event_t *D_PopEvent(void)
{
    event_t *result;

    // No more events waiting.

    if (eventtail == eventhead)
    {
        return NULL;
    }
    
    result = &events[eventtail];

    // Advance to the next event in the queue.

    eventtail = (eventtail + 1) % MAXEVENTS;

    return result;
}

// stores event_t struct in 128-bit value, adding tic number
// in the 32-bit value, containig ev->type. Type takes lower 3 bits,
// others are used to store tic num
__uint128_t pack_event(event_t* ev, unsigned int gametic) {
    __uint128_t packedValue = 0;
    unsigned int type_and_ticnum = (unsigned int)ev->type;
    type_and_ticnum |= (unsigned int)gametic << 3;
    packedValue |= (__uint128_t)(unsigned int)type_and_ticnum << 96;
    packedValue |= (__uint128_t)(unsigned int)ev->data1 << 64;
    packedValue |= (__uint128_t)(unsigned int)ev->data2 << 32;
    packedValue |= (__uint128_t)(unsigned int)ev->data3;
    return packedValue; 
}

// fills "event_t" struct and returns ticnum for event, exatracted from 
// 32-bit field, containing both ev->type (last 3 bits) and ticnum(in other bits)
unsigned int unpack_event(__uint128_t packedValue, event_t *evv) {
    unsigned int tic = packedValue >> 96;
    evv->type = tic & 7;
    evv->data1 = packedValue >> 64;
    evv->data2 = packedValue >> 32;
    evv->data3 = packedValue;

    // skipped these values to keep single event size=128bit
    evv->data4 = 0;
    return tic >> 3; // ticnum
}

